import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarAdmin from "@/components/Layout/SidebarAdmin";
import TanstackProvider from "@/provider/TanstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="flex">
          <div className="ml-64 flex-1 p-6 bg-white min-h-screen">

            <SidebarAdmin />
            <TanstackProvider>
              {children}
            </TanstackProvider>
          </div>

        </div>

      </body>
    </html>
  );
}
